# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d5a42afa21352b1c3fd59a3ceef74dd981fc82a3e50b3a28ccfc1957a85a09065f9ec62aa68e565e6b4467ce972028459235e2ca3bf25f09e68e4dab16a2ddc3

test:
  secret_key_base: 724fd9015ded0fc7a06b5ee5ed3046a78efbeedccf25c39c9b50ba9d0234c5f826f2be8dd3a31447df7d5a9a69d105c9ce56adee8b03b46fc2e0ae837d9cc493

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
